### ISSUE TITLE
Meshes

### ISSUE THREAD

**Issue by Mark-Niemeyer** [agri-gaia/seerep#91]
Implement meshes as data type.

In the end it should be compatible with:
- https://github.com/uos/mesh_navigation/tree/master/mesh_map
- https://github.com/uos/mesh_tools

- https://github.com/uos/pluto_robot/tree/master/pluto_navigation/maps
- https://github.com/uos/mesh_tools

Subtasks:

- [ ] hdf5-io-fb/pb
- [ ] with partial io?
- [ ] indexing (seerep-core)
- [ ] gRPC interface (read/write)

**Comment by jarkenau** [comment]
Tasks to start with:

- [ ] Familiarize with meshes
- https://github.com/uos/mesh_navigation
- Sebastian's PhD Thesis
- https://github.com/uos/mesh_tools
- https://github.com/uos/pluto_robot/tree/master/pluto_navigation/maps
- [ ] Come up with a hdf5 structure, which is compatible with point clouds, so that the point clouds can be extracted from meshes 
- [ ] Mesh message conversions from ROS to fb/pb and vice versa https://docs.ros.org/en/api/mesh_msgs/html/index-msg.html
